### ISSUE TITLE
Select onChange is called 3 times

### ISSUE THREAD

**Issue by EmiBemi** [rmwc/rmwc#854]
- What RMWC Version are you using [major.minor.patch]: 8.0.5

- Name your build system [Webpack, Rollup...]: CRA

- Describe the bug with as much detail as possible:
To see the bug: 
1) go to https://rmwc.io/select-menus
2) scroll down to Controlled / Uncontrolled
3) open developer tool and the console
4) switch between the options
5) observe that the value is being console.log'ed 3 times

**Comment by kintz09** [comment]
I ran into this bug in our projects this week and can confirm its occurring. We are using version 8.0.5, 8.0.6, 8.0.7, and 8.08 in a create react app v4 react typescript project.

Here is a [video](https://drive.google.com/file/d/1EDWm0u_2Its_d08BfXI3Eo_2KZAV9jWt/view?usp=drive_link) I recorded demoing this bug using the documentation website. I verified it occurs with both controlled and uncontrolled instances.

Do we know if this bug is caused by RMWC or could it be a bug in the Material package?

**Comment by kintz09** [comment]
Here is the [changelog](https://github.com/material-components/material-components-web/blob/v8.0.0/CHANGELOG.md) for @material 8.0.0.

It looks like something about change events was fixed:
> select: Deduplicate change events ([4ad1274](https://github.com/material-components/material-components-web/commit/4ad12741e41c5b8e175f2bc8d5053daec6cedf18)), closes https://github.com/material-components/material-components-web/issues/5570
select: do not emit change event when same value selected twice ([e07a708](https://github.com/material-components/material-components-web/commit/e07a7084134b6bbfb1d31a00e410b9d133f28863))

I don't see any other bug fixes related to change events in versions after 8.0.0 so I wouldn't think this is a material bug, but maybe those issues linked above can help us determine the cause of this bug.

**Comment by jensborch** [comment]
This is still an issue, additionally the select documentation is somewhat broken see  https://github.com/rmwc/rmwc/issues/1254 and  https://github.com/rmwc/rmwc/issues/1252
